// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTextSplit
          title="Une expertise de confiance en Rhône-Alpes"
          descriptions={[
            "Forts de notre ancrage local, nous intervenons avec une rigueur absolue pour garantir la pérennité et la valorisation de vos espaces immobiliers.",
            "Qu'il s'agisse de maintenance technique, de rénovation complète ou d'entretien ponctuel, nos équipes qualifiées s'adaptent à vos besoins spécifiques avec discrétion et efficacité.",
            "Notre engagement repose sur une communication transparente, des délais respectés et un savoir-faire reconnu par nos partenaires locaux.",
          ]}
          primaryButton={{
            text: "En savoir plus",
            href: "#services",
          }}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
