// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTextSplit
          title="Une expertise de confiance en Rhône-Alpes"
          descriptions={[
            "Votre intervenant multiservices dédié à l'entretien de locaux professionnels à Lyon. Nous assurons la maintenance immobilière Lyon, le nettoyage de vitrines Lyon et un service d'entretien commerces Lyon sur mesure.",
            "Que vous ayez besoin d'un contrat de maintenance à Lyon, de petits travaux Lyon ou d'un lavage de vitres Lyon régulier ou ponctuel, nos experts multiservices Lyon s'adaptent à toutes vos exigences.",
            "Grâce à nos services de maintenance Lyon, bénéficiez d'un suivi fiable pour l'entretien régulier des locaux professionnels, bureaux et copropriétés.",
          ]}
          primaryButton={{
            text: "En savoir plus",
            href: "#services",
          }}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
