/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import ScrollReveal from "@/components/ui/ScrollReveal";
import TextAnimation from "@/components/ui/TextAnimation";
import Button from "@/components/ui/Button";

const primaryButton = {
  text: "Demander un devis",
  href: "#"
};
const secondaryButton = {
  text: "Appeler le 04 00 00 00 00",
  href: "tel:0400000000"
};

const ContactInline = () => {
  return (
    <section aria-label="Contact section" className="py-20">
      <div className="w-content-width mx-auto">
        <ScrollReveal variant="fade-blur">
          <div className="max-w-2xl mx-auto p-8 md:p-12 rounded card border border-white/10 shadow-2xl">
            <div className="text-center mb-8">
              <div className="px-3 py-1 mb-3 text-sm card rounded w-fit mx-auto text-accent">
                <p>Contact</p>
              </div>
              <h2 className="text-3xl md:text-4xl font-bold text-foreground">
                Contactez-nous
              </h2>
              <p className="text-accent mt-2 text-sm md:text-base">
                Remplissez le formulaire ci-dessous. Nous vous répondrons rapidement.
              </p>
            </div>

            <form className="space-y-5" onSubmit={(e) => e.preventDefault()}>
              <div>
                <label htmlFor="name" className="block text-sm font-medium text-foreground mb-1.5">
                  Nom <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  required
                  placeholder="Votre nom"
                  className="w-full px-4 py-3 rounded bg-background border border-white/15 text-foreground placeholder:text-accent/60 focus:outline-none focus:border-red-500 transition-colors"
                />
              </div>

              <div>
                <label htmlFor="email" className="block text-sm font-medium text-foreground mb-1.5">
                  Email <span className="text-red-500">*</span>
                </label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  required
                  placeholder="votre.email@exemple.com"
                  className="w-full px-4 py-3 rounded bg-background border border-white/15 text-foreground placeholder:text-accent/60 focus:outline-none focus:border-red-500 transition-colors"
                />
              </div>

              <div>
                <label htmlFor="message" className="block text-sm font-medium text-foreground mb-1.5">
                  Message <span className="text-red-500">*</span>
                </label>
                <textarea
                  id="message"
                  name="message"
                  required
                  rows={4}
                  placeholder="Décrivez votre besoin..."
                  className="w-full px-4 py-3 rounded bg-background border border-white/15 text-foreground placeholder:text-accent/60 focus:outline-none focus:border-red-500 transition-colors resize-none"
                />
              </div>

              <button
                type="submit"
                className="w-full py-3.5 px-6 rounded primary-button font-medium text-white shadow-lg hover:opacity-90 transition-opacity cursor-pointer"
              >
                Envoyer le message
              </button>
            </form>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function ContactSection() {
  return (
    <div data-webild-section="contact" data-section="contact" id="contact">
      <ContactInline />
    </div>
  );
}
