// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Contact"
          text="Prêt à valoriser vos espaces ? Contactez nos experts dès maintenant pour une étude personnalisée."
          primaryButton={{
            text: "Demander un devis",
            href: "#",
          }}
          secondaryButton={{
            text: "Appeler le 04 00 00 00 00",
            href: "tel:0400000000",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
