// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSplitMedia from '@/components/sections/faq/FaqSplitMedia';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSplitMedia
          tag="Questions fréquentes"
          title="Besoin d'informations ?"
          description="Voici les réponses aux questions les plus courantes sur nos services de maintenance."
          items={[
            {
              question: "Quels types de bâtiments entretenez-vous ?",
              answer: "Nous intervenons dans les résidences privées, les locaux commerciaux, les bureaux, les écoles et les hôtels de la région.",
            },
            {
              question: "Comment demander un devis gratuit ?",
              answer: "Il vous suffit de nous contacter via le formulaire dédié ou par téléphone. Nous établissons un diagnostic sous 48h.",
            },
            {
              question: "Proposez-vous des contrats de maintenance ?",
              answer: "Oui, nous mettons en place des contrats sur-mesure pour un entretien régulier et serein de vos installations.",
            },
            {
              question: "Intervenez-vous en urgence ?",
              answer: "Nous disposons d'une équipe dédiée aux interventions rapides pour résoudre les problèmes critiques rapidement.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/young-woman-man-working-together-blueprint-office_23-2148203996.jpg"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
