// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsFeatureCards from '@/components/sections/metrics/MetricsFeatureCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsFeatureCards
          tag="Pourquoi nous choisir"
          title="Des indicateurs de réussite"
          description="La satisfaction client est au cœur de notre démarche quotidienne."
          metrics={[
            {
              value: "98%",
              title: "Satisfaction client",
              features: [
                "Transparence totale",
                "Suivi rigoureux",
                "Équipes dédiées",
              ],
            },
            {
              value: "12h",
              title: "Temps de réponse",
              features: [
                "Réactivité maximale",
                "Interventions express",
                "Disponibilité",
              ],
            },
            {
              value: "200+",
              title: "Projets réalisés",
              features: [
                "Expertise confirmée",
                "Références solides",
                "Savoir-faire",
              ],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
