// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesRevealCardsBento
          tag="Services"
          title="Nos domaines d'intervention"
          description="Une gamme complète de prestations pour répondre à vos exigences de maintenance et de rénovation."
          items={[
            {
              title: "Maintenance Technique",
              description: "Diagnostic et entretien préventif complet de vos installations.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/full-shot-men-wearing-equipment_23-2149345538.jpg",
            },
            {
              title: "Rénovation Intérieure",
              description: "Craftsmanship de haute qualité pour vos projets de transformation.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/male-electrician-working-electrical-panel-male-electrician-overalls_169016-67163.jpg",
            },
            {
              title: "Entretien de Locaux",
              description: "Nettoyage quotidien ou périodique pour entreprises et commerces.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-young-beautiful-woman-gesticulating_273609-40342.jpg",
            },
            {
              title: "Services de Proximité",
              description: "Une équipe réactive pour vos besoins de réparation rapide.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/empty-space-car-park-interior-night_1127-2306.jpg",
            },
            {
              title: "Rénovation Façades",
              description: "Valorisez l'extérieur de votre bâtiment avec nos solutions.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/monochrome-scene-depicting-life-workers-construction-industry-site_23-2151431465.jpg",
            },
            {
              title: "Interventions d'Urgence",
              description: "Réponse rapide pour assurer la continuité de vos activités.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/front-view-male-builder-uniform-holding-black-bank-card-yellow-background_140725-112415.jpg",
            },
            {
              title: "Projets Sur-Mesure",
              description: "Solutions personnalisées selon vos objectifs de valorisation.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-happy-auto-repairman-looking-camera-while-his-customers-are-standing-background_637285-7790.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
