// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialColumnMarqueeCards from '@/components/sections/testimonial/TestimonialColumnMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialColumnMarqueeCards
          tag="Témoignages"
          title="La confiance de nos partenaires"
          description="Découvrez les retours de nos clients satisfaits par notre accompagnement."
          testimonials={[
            {
              name: "Marc Dubois",
              role: "Gestionnaire Immobilier",
              quote: "Un service irréprochable et des équipes toujours très réactives pour les urgences sur nos sites.",
              imageSrc: "http://img.b2bpic.net/free-photo/beautiful-female-real-estate-agent-standing-house-entrance-smiling-woman-with-short-graying-hair-pink-suit-getting-ready-meet-customers-real-estate-business-work-concept_74855-22183.jpg",
            },
            {
              name: "Sophie Martin",
              role: "Propriétaire",
              quote: "La rénovation de notre appartement a été gérée avec professionnalisme et un souci du détail exemplaire.",
              imageSrc: "http://img.b2bpic.net/free-photo/men-working-together-medium-shot_52683-101624.jpg",
            },
            {
              name: "Alexandre Petit",
              role: "Directeur d'Hôtel",
              quote: "Rhône Alpes Services est devenu notre partenaire de confiance pour tout l'entretien de notre établissement.",
              imageSrc: "http://img.b2bpic.net/free-photo/confident-chef-wearing-uniform-posing-with-his-arms-crossed-looking-away-restaurant-kitchen_613910-18965.jpg",
            },
            {
              name: "Julie Laurent",
              role: "Gérante de Magasin",
              quote: "Enfin une équipe qui comprend nos contraintes professionnelles et intervient avec un minimum de gêne.",
              imageSrc: "http://img.b2bpic.net/free-photo/businesswoman-holding-plan_23-2147704439.jpg",
            },
            {
              name: "Thomas Bernard",
              role: "Syndic d'Immeuble",
              quote: "Une transparence totale dans les devis et des travaux toujours réalisés selon les normes et les délais annoncés.",
              imageSrc: "http://img.b2bpic.net/free-photo/young-couple-moving-new-home-together-african-american-couple-with-cardboard-boxes_1157-40328.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
