// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "trust" section.

import React from 'react';
import SocialProofMarquee from '@/components/sections/social-proof/SocialProofMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TrustSection(): React.JSX.Element {
  return (
    <div id="trust" data-section="trust">
        <SectionErrorBoundary name="trust">
              <SocialProofMarquee
          tag="Nos partenaires"
          title="Ils nous font confiance"
          description="Nous accompagnons des acteurs de référence dans tout le secteur Rhône-Alpes."
          names={[
            "Immo Lyon",
            "Entreprise Services",
            "Rénov'Habit",
            "Gestion Immo",
            "Commerces Rhône",
            "Bâtir Ensemble",
            "Services Pro",
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
